#!/bin/bash

# Top Function Target
export WORKLOAD=YuvToRgb_f2r_forBody_s2e_forEndLoopexit

# Env. Variables needed.
export LLVM_HOME=~giorgio/llvm-3.4/build/
export TRACER_HOME=~giorgio/LLVM-Tracer/build/
