#!/bin/bash

# Top Function Target
export WORKLOAD=WriteOneBlock_f2r_WriteOneBlock
#Write4Blocks_f2r_WriteOneBlockExit121_s2e_WriteOneBlockExit93 

# Env. Variables needed.
export LLVM_HOME=~giorgio/llvm-3.4/build/
export TRACER_HOME=~giorgio/LLVM-Tracer/build/
