#!/bin/bash

# Top Function Target
export WORKLOAD=decode_start_f2r_vectorBody_s2e_YuvToRgbExit324 

# Env. Variables needed.
export LLVM_HOME=~giorgio/llvm-3.4/build/
export TRACER_HOME=~giorgio/LLVM-Tracer/build/
