#!/bin/bash

# Top Function Target
export WORKLOAD=Write4Blocks_f2r_WriteOneBlockExit93_s2e_WriteOneBlockExit65

# Env. Variables needed.
export LLVM_HOME=~giorgio/llvm-3.4/build/
export TRACER_HOME=~giorgio/LLVM-Tracer/build/
