#!/bin/bash

# Top Function Target
export WORKLOAD=BoundIDctMatrix_f2r_BoundIDctMatrix

# Env. Variables needed.
export LLVM_HOME=~giorgio/llvm-3.4/build/
export TRACER_HOME=~giorgio/LLVM-Tracer/build/
