#!/bin/bash

# Top Function Target
export WORKLOAD=Write4Blocks_f2r_WriteOneBlockExit_s2e_WriteOneBlockExit121

# Env. Variables needed.
export LLVM_HOME=~giorgio/llvm-3.4/build/
export TRACER_HOME=~giorgio/LLVM-Tracer/build/
